
package p1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RhServiceImplService", targetNamespace = "http://p1/", wsdlLocation = "http://localhost:8086/myWebService?wsdl")
public class RhServiceImplService
    extends Service
{

    private final static URL RHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RHSERVICEIMPLSERVICE_QNAME = new QName("http://p1/", "RhServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/myWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RhServiceImplService() {
        super(__getWsdlLocation(), RHSERVICEIMPLSERVICE_QNAME);
    }

    public RhServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RHSERVICEIMPLSERVICE_QNAME, features);
    }

    public RhServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RHSERVICEIMPLSERVICE_QNAME);
    }

    public RhServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RHSERVICEIMPLSERVICE_QNAME, features);
    }

    public RhServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RhServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RhService
     */
    @WebEndpoint(name = "RhServiceImplPort")
    public RhService getRhServiceImplPort() {
        return super.getPort(new QName("http://p1/", "RhServiceImplPort"), RhService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RhService
     */
    @WebEndpoint(name = "RhServiceImplPort")
    public RhService getRhServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://p1/", "RhServiceImplPort"), RhService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
