
package p1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RhService", targetNamespace = "http://p1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RhService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://p1/", className = "p1.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://p1/", className = "p1.DeleteEmployeeResponse")
    @Action(input = "http://p1/RhService/deleteEmployeeRequest", output = "http://p1/RhService/deleteEmployeeResponse")
    public String deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<p1.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getemployees", targetNamespace = "http://p1/", className = "p1.Getemployees")
    @ResponseWrapper(localName = "getemployeesResponse", targetNamespace = "http://p1/", className = "p1.GetemployeesResponse")
    @Action(input = "http://p1/RhService/getemployeesRequest", output = "http://p1/RhService/getemployeesResponse")
    public List<Employee> getemployees();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://p1/", className = "p1.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://p1/", className = "p1.UpdateEmployeeResponse")
    @Action(input = "http://p1/RhService/updateEmployeeRequest", output = "http://p1/RhService/updateEmployeeResponse")
    public String updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns p1.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://p1/", className = "p1.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://p1/", className = "p1.GetEmployeeByIdResponse")
    @Action(input = "http://p1/RhService/getEmployeeByIdRequest", output = "http://p1/RhService/getEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://p1/", className = "p1.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://p1/", className = "p1.AddEmployeeResponse")
    @Action(input = "http://p1/RhService/addEmployeeRequest", output = "http://p1/RhService/addEmployeeResponse")
    public String addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<p1.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchEmployees", targetNamespace = "http://p1/", className = "p1.SearchEmployees")
    @ResponseWrapper(localName = "searchEmployeesResponse", targetNamespace = "http://p1/", className = "p1.SearchEmployeesResponse")
    @Action(input = "http://p1/RhService/searchEmployeesRequest", output = "http://p1/RhService/searchEmployeesResponse")
    public List<Employee> searchEmployees(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
